name: selectManager
description: Manage and Sort items between 2 select boxes
author: Trevor Orr
category: Utilities
tags: [select, form, sort, options]
current: 1.0
license: MIT License
demo: http://jsfiddle.net/fractorr/VGTGc/